### ISSUE TITLE
Error in replicating multiple font loading

### ISSUE THREAD

**Issue by w9914420** [kevanstannard/three#1]
Good Evening

I have been looking at your source code for one of your experiments:
[multiple fonts](https://github.com/kevanstannard/three/blob/master/src/experiments/multiple-fonts/index.js)

And I am not having any success with recreating it, I assume that you have used web pack to create the example. because the git code and your bundle.js code are completely different.

I wonder if you could shed some light onto how you create this, and maybe a native javascript example if possible. 
Your Simple font example:
[Simple font example](https://kevanstannard.github.io/three/dist/experiments/simple-font/index.html) works without any issues.

regards

Mr W.

**Comment by kevanstannard** [comment]
Hi Mr W, yes this one was a bit more involved.

I'm guessing the problem might be related to the initially loading the multiple fonts? The three.js font loader is designed for just one font at a time so in the Multiple Fonts experiment I've created a module to handle loading the fonts:

https://github.com/kevanstannard/three/blob/master/src/modules/fonts/index.js

Can you tell me a bit more about how you are trying to re-create the experiments? That will help me understand where the problem might be. Also, let me know if you see any errors in the console when you run your version of the code.

**Comment by w9914420** [comment]
Hi Kevanstannard

Thanks for the quick reply. In regards to what I was trying to recreate I wanted to implement the multiple font feature into my own project. So in effect all I did was to copy the methods and functions to my own project from the git repository link located on the experiment page.

This naturally did not work and it was only having taking a proper look at your code that I released you must be using webpack to do the exporting of modules to make it work and that the code actual refers to source code and not complied code for the browser.

I downloaded you repository and ran it on my server and it works as expected, however if I take the 'dist' files from within your repository and place them within my root (_rename relative links whereas_) and try to run the experiment if gives me a 404 error in regards to placement of the fonts

![screen shot 2017-03-12 at 14 44 22](https://cloud.githubusercontent.com/assets/4603772/23832718/8647f5d8-0732-11e7-88c2-8976c3daac22.png)

I noticed in the bundle file that there is reference to the loading url

![screen shot 2017-03-12 at 14 46 36](https://cloud.githubusercontent.com/assets/4603772/23832722/c38512e6-0732-11e7-8921-4757c684705f.png)

I assumed that I would be able to change the url to the relevant path but this still gives me the same error. So I assumed that you need weback to run your experiments, the only problem is that I am not working in such an environment and wondered if there was another way achive the same effect with just native javascript.

P.s Thanks again you code is teaching me alot!!

Mr W

**Comment by kevanstannard** [comment]
Hi Mr W, here's some code you can add to your program. Not tested but should hopefully give you the idea.

```js
var fontLoader = new THREE.FontLoader();

var fonts = {};

function loadFont(name) {
  var url = '../../modules/fonts/fonts/' + name + '.typeface.json';
  return new Promise(function(resolve) {
    fontLoader.load(url, function(font) {
      fonts[name] = font;
      resolve();
    });
  });
}

function loadFonts() {
  var promises = [
    loadFont('gentilis_regular'),
    loadFont('helvetiker_regular'),
    loadFont('optimer_regular'),
  ];
  return Promise.all(promises);
}

function start() {
  // Main code here
}

loadFonts().then(start);
```

**Comment by w9914420** [comment]
@kevanstannard many thanks for this,

 It works perfectly for me.
