### ISSUE TITLE
https://kevanstannard.github.io pages not found

### ISSUE THREAD

**Issue by w9914420** [kevanstannard/three#2]
Hi Kevanstannard,

Just went back to your online experiments to show a friend of mine your work and was greeted with 404 pages. I hope you have not decided to take them down because you have some of the best three.js examples out on the internet. It would be sad to not have them available.

regards

W9914420

**Comment by kevanstannard** [comment]
Hi W9914420, thanks for letting me know. I renamed the repository, you can find them here now:

https://kevanstannard.github.io/three-experiments/

**Comment by w9914420** [comment]
Hi KevanStannard

Many tnxs :)
